infra:
    mongodb:
        first:
            host:
            port:
            name: first
            username: root
            password: 'test1234'
        second:
            host:
            port:
            name: second
            username:
            password:
        third:
            host:
            port:
            name: third
            username:
            password: '!1026Antock!'

spring:
    data:
        mongodb:
            first:
                database: ${infra.mongodb.rawdata.name}
                uri: mongodb://${infra.mongodb.rawdata.username}:${infra.mongodb.rawdata.password}@${infra.mongodb.rawdata.host}:${infra.mongodb.rawdata.port}/${infra.mongodb.rawdata.name}?connectTimeoutMS=100000&minPoolSize=0&maxPoolSize=16
            second:
                database: ${infra.mongodb.rawdata.name}
                uri: mongodb://${infra.mongodb.rawdata.username}:${infra.mongodb.rawdata.password}@${infra.mongodb.rawdata.host}:${infra.mongodb.rawdata.port}/${infra.mongodb.rawdata.name}?connectTimeoutMS=100000&minPoolSize=0&maxPoolSize=16
            third:
                database: ${infra.mongodb.rawdata.name}
                uri: mongodb://${infra.mongodb.rawdata.username}:${infra.mongodb.rawdata.password}@${infra.mongodb.rawdata.host}:${infra.mongodb.rawdata.port}/${infra.mongodb.rawdata.name}?connectTimeoutMS=100000&minPoolSize=0&maxPoolSize=16